version: '3'
networks:
  web-app-network:
    driver: bridge
services:
  minio:
    image: minio/minio:RELEASE.2024-03-05T04-48-44Z
    container_name: web-app-network-minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/root/.minio:/root/.minio
    networks:
      - web-app-network
  postgresql:
    restart: always
    image: postgres:16.2
    #    shm_size: 256mb # 设置共享内存大小
    container_name: web-app-network-pgsql
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Shanghai
    volumes:
      - ./docker/pgsql/data:/var/lib/postgresql/data
      - ./docker/pgsql/log:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - web-app-network
  redis:
    image: redis:6
    container_name: web-app-network-redis
    restart: always
    env_file: .env
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - web-app-network