version: '3'
networks:
  sunnysunco-web-network:
    driver: bridge
services:
  minio:
    image: minio/minio:RELEASE.2024-03-05T04-48-44Z
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sunnysunco
      MINIO_ROOT_PASSWORD: sunnysunco
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/root/.minio:/root/.minio
    networks:
      - sunnysunco-web-network
  redis:
    image: redis:6
    container_name: cloud-redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    command: [ "redis-server", "--requirepass", "sunnysunco", "--appendonly", "yes" ]
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - sunnysunco-web-network